steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/quix-demo/frontend', './quix-frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/quix-demo/backend', './quix-backend']
images: ['gcr.io/quix-demo/frontend', 'gcr.io/quix-demo/backend']
